routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/customer/{id?}', function ($id=null) {
    if($id == null){
        return "No customer was provided";
    }
    return view("customers",['id'=>$id]);
});

//Route::resource('books','BookController')->middleware('auth');
Route::resource('books','BookController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    //database fields to be allowed for massive assignment
    protected $fillable=['title','author','status'];

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    public function books(){
        return $this->hasMany('App\Book');
    }
    use Notifiable;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Book;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id=Auth::id();
        //$id=1;
       // $books=Book::all();
       $books=User::find($id)->books;
        return view('Books.index', ['books'=>$books]);

        

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $book = new Book();
        $id =1;
        $book->title= $request->title;
        $book->author= $request->author;
        $book->user_id=$id;
        $book->status=0;
        $book->save();
        return redirect('books');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book=Book::find($id);
        return view('Books.edit',['book'=>$book]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book=Book::find($id);
        if(!$book->user->id==Auth::id()) return(redirect('books'));
        $book->update($request->except(['_token']));
        if($request->ajax()){
            return Response::json(array('result'=>'success','status'=>$request->status),200);
        }
        return redirect('books');
        //$book->update($request->all());
       // return redirect('books');
    }

    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
 
        $book = Book::find($id);
        if(!$book->user->id==Auth::id()) return(redirect('books'));
        $book->delete();
        return redirect('books');

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/Books/create.blade.php
@extends('layouts.app')
@section('content')
<h1>Create a new book</h1>
<form method='post' action="{{action('BookController@store')}}">
    {{csrf_field()}}
    <div class="form-group">
        <label for ="title"> what whould you like read?</label>
        <input type="text" class= "form-control" name="title">
        <label for ="author">who is the author?</label>
        <input type="text" class= "form-control" name="author">
    </div>
    <div class = "form-group">
        <input type="submit" class="form-controll" name="submit" value="save">
    </div>
</form>
@endsection

resources/views/Books/edit.blade.php
@extends('layouts.app')
@section('content')
<h1>Update a Book</h1>
<form method='post' action="{{action('BookController@update', $book->id )}}">
    @csrf
    @method('PATCH')
    <div class="form-group">
        <label for ="title"> Book to Update:</label>
        <input type="text" class= "form-control" name="title" value="{{$book->title}}">
    </div>
    <div>
        
        <input type="text" class= "form-control" name="author" value="{{$book->author}}">
    </div>
    <div class = "form-group">
    <input type = "submit" class = "form-control" name = "submit" value = "update" >
    </div>
</form>

<form method='post' action="{{action('BookController@destroy', $book->id)}}">
    @csrf
   @method('DELETE')
    <div class = "form-group">
        <input type="submit" class="form-control" name="submit" value="Delete">
    </div>
</form>
@endsection

resources/views/Books/index.blade.php
@extends('layouts.app')
@section('content')
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <table>
            <tr>
            
                <th>title</th>
                <th>author</th>
            </tr>
            @foreach($books as $book)
            <tr>
           <td> @if ($book->status)
                 <input type = 'checkbox' id ="{{$book->id}}" checked>
            @else
                <input type = 'checkbox' id ="{{$book->id}}">
            @endif
            </td>
               <td><a href="{{route('books.edit',$book->id)}}">  {{$book->title}}</a></td>

              <td><a href="{{route('books.edit',$book->id)}}">  {{$book->author}}</a></td>
            </tr>
            @endforeach
        </table>
        <a href= "{{route('books.create')}}">Create a new book</a>
        <script>
       $(document).ready(function(){
           $(":checkbox").click(function(event){
               $.ajax({
                   url:  {{url('books')}}+'/'+event.target.id),
                   dataType: 'json',
                   type: 'put' ,
                   contentType: 'application/json',
                   data: JSON.stringify({'status':event.target.checked, _token:'{{csrf_token()}}'}),
                   processData:false,
                   success: function( data){
                        console.log(JSON.stringify( data ));
                   },
                   error: function(errorThrown ){
                       console.log( errorThrown );
                   }
               });               
           });
       });
   </script>

    </body>
</html>
@endsection

resources/views/customers.blade.php
<h1>
welcome customer number {{$id}}
</h1>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>